/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudyScheduleGeneratorRouteImport } from './routes/study-schedule-generator'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamRouteImport } from './routes/_authenticated/exam'
import { Route as AuthenticatedImageStudioRouteImport } from './routes/_authenticated/image-studio'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedOwnerRouteRouteImport } from './routes/_authenticated/owner/route'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSiteSettingsRouteImport } from './routes/_authenticated/site-settings'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner/index'
import { Route as AuthenticatedOwnerAnnouncementsRouteImport } from './routes/_authenticated/owner/announcements'
import { Route as AuthenticatedOwnerFeedbackRouteImport } from './routes/_authenticated/owner/feedback'
import { Route as AuthenticatedDocumentsDocumentIdIndexRouteImport } from './routes/_authenticated/documents/$documentId/index'
import { Route as AuthenticatedDocumentsDocumentIdChatThreadIdRouteImport } from './routes/_authenticated/documents/$documentId/chat/$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyScheduleGeneratorRoute = StudyScheduleGeneratorRouteImport.update({
  id: '/study-schedule-generator',
  path: '/study-schedule-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamRoute = AuthenticatedExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImageStudioRoute =
  AuthenticatedImageStudioRouteImport.update({
    id: '/image-studio',
    path: '/image-studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRouteRoute = AuthenticatedOwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiteSettingsRoute =
  AuthenticatedSiteSettingsRouteImport.update({
    id: '/site-settings',
    path: '/site-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOwnerRouteRoute,
} as any)
const AuthenticatedOwnerAnnouncementsRoute =
  AuthenticatedOwnerAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)
const AuthenticatedOwnerFeedbackRoute =
  AuthenticatedOwnerFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedOwnerRouteRoute,
  } as any)
const AuthenticatedDocumentsDocumentIdIndexRoute =
  AuthenticatedDocumentsDocumentIdIndexRouteImport.update({
    id: '/documents/$documentId/',
    path: '/documents/$documentId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocumentIdChatThreadIdRoute =
  AuthenticatedDocumentsDocumentIdChatThreadIdRouteImport.update({
    id: '/documents/$documentId/chat/$threadId',
    path: '/documents/$documentId/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-schedule-generator': typeof StudyScheduleGeneratorRoute
  '/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/image-studio': typeof AuthenticatedImageStudioRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/site-settings': typeof AuthenticatedSiteSettingsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/owner/announcements': typeof AuthenticatedOwnerAnnouncementsRoute
  '/owner/feedback': typeof AuthenticatedOwnerFeedbackRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/documents/$documentId/': typeof AuthenticatedDocumentsDocumentIdIndexRoute
  '/documents/$documentId/chat/$threadId': typeof AuthenticatedDocumentsDocumentIdChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-schedule-generator': typeof StudyScheduleGeneratorRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/image-studio': typeof AuthenticatedImageStudioRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/site-settings': typeof AuthenticatedSiteSettingsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/owner/announcements': typeof AuthenticatedOwnerAnnouncementsRoute
  '/owner/feedback': typeof AuthenticatedOwnerFeedbackRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdIndexRoute
  '/documents/$documentId/chat/$threadId': typeof AuthenticatedDocumentsDocumentIdChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-schedule-generator': typeof StudyScheduleGeneratorRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exam': typeof AuthenticatedExamRoute
  '/_authenticated/image-studio': typeof AuthenticatedImageStudioRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/site-settings': typeof AuthenticatedSiteSettingsRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/_authenticated/owner/announcements': typeof AuthenticatedOwnerAnnouncementsRoute
  '/_authenticated/owner/feedback': typeof AuthenticatedOwnerFeedbackRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/documents/$documentId/': typeof AuthenticatedDocumentsDocumentIdIndexRoute
  '/_authenticated/documents/$documentId/chat/$threadId': typeof AuthenticatedDocumentsDocumentIdChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/study-schedule-generator'
    | '/owner'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/exam'
    | '/image-studio'
    | '/library'
    | '/planner'
    | '/progress'
    | '/review'
    | '/settings'
    | '/site-settings'
    | '/sources'
    | '/voice'
    | '/api/generate-image'
    | '/owner/announcements'
    | '/owner/feedback'
    | '/documents/'
    | '/owner/'
    | '/documents/$documentId/'
    | '/documents/$documentId/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/study-schedule-generator'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/exam'
    | '/image-studio'
    | '/library'
    | '/planner'
    | '/progress'
    | '/review'
    | '/settings'
    | '/site-settings'
    | '/sources'
    | '/voice'
    | '/api/generate-image'
    | '/owner/announcements'
    | '/owner/feedback'
    | '/documents'
    | '/owner'
    | '/documents/$documentId'
    | '/documents/$documentId/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/study-schedule-generator'
    | '/_authenticated/owner'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/exam'
    | '/_authenticated/image-studio'
    | '/_authenticated/library'
    | '/_authenticated/planner'
    | '/_authenticated/progress'
    | '/_authenticated/review'
    | '/_authenticated/settings'
    | '/_authenticated/site-settings'
    | '/_authenticated/sources'
    | '/_authenticated/voice'
    | '/api/generate-image'
    | '/_authenticated/owner/announcements'
    | '/_authenticated/owner/feedback'
    | '/_authenticated/documents/'
    | '/_authenticated/owner/'
    | '/_authenticated/documents/$documentId/'
    | '/_authenticated/documents/$documentId/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyScheduleGeneratorRoute: typeof StudyScheduleGeneratorRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-schedule-generator': {
      id: '/study-schedule-generator'
      path: '/study-schedule-generator'
      fullPath: '/study-schedule-generator'
      preLoaderRoute: typeof StudyScheduleGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam': {
      id: '/_authenticated/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthenticatedExamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/image-studio': {
      id: '/_authenticated/image-studio'
      path: '/image-studio'
      fullPath: '/image-studio'
      preLoaderRoute: typeof AuthenticatedImageStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-settings': {
      id: '/_authenticated/site-settings'
      path: '/site-settings'
      fullPath: '/site-settings'
      preLoaderRoute: typeof AuthenticatedSiteSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/owner/announcements': {
      id: '/_authenticated/owner/announcements'
      path: '/announcements'
      fullPath: '/owner/announcements'
      preLoaderRoute: typeof AuthenticatedOwnerAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/owner/feedback': {
      id: '/_authenticated/owner/feedback'
      path: '/feedback'
      fullPath: '/owner/feedback'
      preLoaderRoute: typeof AuthenticatedOwnerFeedbackRouteImport
      parentRoute: typeof AuthenticatedOwnerRouteRoute
    }
    '/_authenticated/documents/$documentId/': {
      id: '/_authenticated/documents/$documentId/'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId/'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$documentId/chat/$threadId': {
      id: '/_authenticated/documents/$documentId/chat/$threadId'
      path: '/documents/$documentId/chat/$threadId'
      fullPath: '/documents/$documentId/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedOwnerRouteRouteChildren {
  AuthenticatedOwnerAnnouncementsRoute: typeof AuthenticatedOwnerAnnouncementsRoute
  AuthenticatedOwnerFeedbackRoute: typeof AuthenticatedOwnerFeedbackRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
}

const AuthenticatedOwnerRouteRouteChildren: AuthenticatedOwnerRouteRouteChildren =
  {
    AuthenticatedOwnerAnnouncementsRoute: AuthenticatedOwnerAnnouncementsRoute,
    AuthenticatedOwnerFeedbackRoute: AuthenticatedOwnerFeedbackRoute,
    AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
  }

const AuthenticatedOwnerRouteRouteWithChildren =
  AuthenticatedOwnerRouteRoute._addFileChildren(
    AuthenticatedOwnerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOwnerRouteRoute: typeof AuthenticatedOwnerRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamRoute: typeof AuthenticatedExamRoute
  AuthenticatedImageStudioRoute: typeof AuthenticatedImageStudioRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSiteSettingsRoute: typeof AuthenticatedSiteSettingsRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedDocumentsDocumentIdIndexRoute: typeof AuthenticatedDocumentsDocumentIdIndexRoute
  AuthenticatedDocumentsDocumentIdChatThreadIdRoute: typeof AuthenticatedDocumentsDocumentIdChatThreadIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOwnerRouteRoute: AuthenticatedOwnerRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamRoute: AuthenticatedExamRoute,
  AuthenticatedImageStudioRoute: AuthenticatedImageStudioRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSiteSettingsRoute: AuthenticatedSiteSettingsRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedDocumentsDocumentIdIndexRoute:
    AuthenticatedDocumentsDocumentIdIndexRoute,
  AuthenticatedDocumentsDocumentIdChatThreadIdRoute:
    AuthenticatedDocumentsDocumentIdChatThreadIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyScheduleGeneratorRoute: StudyScheduleGeneratorRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
